apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deep-ion-db
resources:
  - namespace.yaml
  - secret.yaml # crie a partir de secret.example.yaml
  - postgres.yaml
  - server.yaml
  # - ingress.yaml   # habilite se tiver um ingress controller
